name: cbheck vars

on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      EXAMPLE_VAR: ${{ vars.SAMPLE_VAR }}"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: check vars
        run: echo ${{ env.EXAMPLE_VAR }}
