name: cbheck vars

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: check vars
        run: echo ${{ vars.SAMPLE_VAR }}
